#!/bin/bash

ARGS=2
E_BADARGS=127

if [ $# -ne "$ARGS" ]
then
    echo "Execution order `basename $0` first and second number"
    exit $E_BADARGS
fi

gcd ()
{
    dividend=$1
    divisor=$2
    remainder=1
    until [ "$remainder" -eq 0 ]
    do
        let "remainder = $dividend % $divisor"
        dividend=$divisor
        divisor=$remainder
    done

    return $dividend
}
 
gcd $1 $2

echo; echo "NOD $1 and $2 : $dividend "; echo